services:
  zm:
    image: zoneminder
    build: .
#    devices:
#      - "/dev/video0:/dev/video0:rw"
    shm_size: "2GB"
#    network_mode: host
    ports:
      - "80:80"
      - "9000:9000"
    environment:
      - TZ=Asia/Jakarta
      - DB_USER=zmuser
      - DB_PASS=zmpass
      - INSTALL_ZMES=1
    volumes:
      - /srv/zoneminder/config:/srv/config
      - /srv/zoneminder/data:/srv/data
