services:
  zoneminder:
    container_name: zoneminder
    image: zoneminder
#    devices:
#      - "/dev/video0:/dev/video0:rw"
#    network_mode: host
    shm_size: "2GB"
    ports:
      - "80:80"
      - "9000:9000"
    environment:
      - TZ=Asia/Jakarta
      - DB_USER=zmuser
      - DB_PASS=zmpass
      - INSTALL_ZMES=1
      - INSTALL_HOOK=1
      - INSTALL_MODEL=1
    volumes:
      - /srv/zoneminder/config:/srv/config:rw
      - /srv/zoneminder/data:/srv/data:rw
